MvcUtopiaAWSAMH/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using MvcUtopiaAWSAMH.Filters;
using MvcUtopiaAWSAMH.Services;
using NugetUtopia;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcUtopiaAWSAMH.Controllers
{
    public class AdminController : Controller
    {
        private ServiceApiUtopia service;

        public AdminController(ServiceApiUtopia service)
        {
            this.service = service;
        }

        [AuthorizeUsuarios(Policy = "AdminOnly")]
        public async Task<IActionResult> Index()
        {
            string token = HttpContext.User.FindFirst("TOKEN").Value;
            List<Plato> platos = await this.service.GetPlatosAsync();
            List<Juego> juegos = await this.service.GetJuegosAsync();
            List<Reserva> reservas = await this.service.GetReservasAsync(token);

            ViewData["PLATOS"] = platos;
            ViewData["JUEGOS"] = juegos;
            return View(reservas);
        }
    }
}

MvcUtopiaAWSAMH/Controllers/JuegosController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MvcUtopiaAWSAMH.Filters;
using MvcUtopiaAWSAMH.Services;
using NugetUtopia;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace MvcUtopiaAWSAMH.Controllers
{
    public class JuegosController : Controller
    {
        private ServiceApiUtopia service;

        public JuegosController(ServiceApiUtopia service)
        {
            this.service = service;
        }

        public async Task<IActionResult> Index()
        {
            List<Juego> juegos = await this.service.GetJuegosAsync();
            HttpContext.Session.GetString("PRUEBA");
            return View(juegos);
           
        }

        [AuthorizeUsuarios(Policy = "AdminOnly")]
        public IActionResult CrearJuego()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> CrearJuego(int idjuego, string nombre, string descripcion, string categoria, int precio, IFormFile foto)
        {
            string filename = foto.FileName;
            string token = HttpContext.User.FindFirst("TOKEN").Value;
            Juego juego = new Juego();
            juego.IdJuego = idjuego;
            juego.Nombre = nombre;
            juego.Descripcion = descripcion;
            juego.Categoria = categoria;
            juego.Precio = precio;
            juego.Foto = filename;
            await this.service.CrearJuegoAsync(juego, token);

            using (Stream stream = foto.OpenReadStream())
            {
                await this.service.UploadFile(stream, foto.FileName,"juegos");
            }
            return RedirectToAction("Index", "Admin");
        }

        [AuthorizeUsuarios(Policy = "AdminOnly")]
        public async Task<ActionResult> DeleteJuego(int idjuego)
        {
            string token = HttpContext.User.FindFirst("TOKEN").Value;
            Juego juego = await this.service.FindJuegoAsync(idjuego);
            await this.service.DeleteFileAsync(juego.Foto, "juegos");
            await this.service.DeleteJuegoAsync(idjuego, token);
            return RedirectToAction("Index", "Admin");
        }

        [AuthorizeUsuarios(Policy = "AdminOnly")]
        public async Task<IActionResult> EditarJuego(int idjuego)
        {
            Juego juego = await this.service.FindJuegoAsync(idjuego);
            return View(juego);
        }

        [HttpPost]
        public async Task<IActionResult> EditarJuego(Juego juego, IFormFile archivo)
        {
            await this.service.DeleteFileAsync(juego.Foto,"juegos");

            string filename = archivo.FileName;
            string token = HttpContext.User.FindFirst("TOKEN").Value;
            juego.Foto = filename;
            await this.service.UpdateJuegoAsync(juego, token);

            using (Stream stream = archivo.OpenReadStream())
            {
                await this.service.UploadFile(stream, archivo.FileName, "juegos");
            }

            return RedirectToAction("Index", "Admin");
        }

        [AuthorizeUsuarios]
        public IActionResult Favoritos()
        {
            int idusuario = int.Parse(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
            List<Juego> favoritos =
                this.service.GetFavorito(idusuario);
            if (favoritos == null)
            {
                return View();
            }
            else
            {
                return View(favoritos);
            }
        }

        [AuthorizeUsuarios]
        public async Task<IActionResult> SeleccionarFavorito(int idjuego)
        {
            int idusuario = int.Parse(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
            Juego favorito = await this.service.FindJuegoAsync(idjuego);
            this.service.AddFavorito(favorito, idusuario);
            return RedirectToAction("Favoritos");
        }

        [AuthorizeUsuarios]
        public IActionResult EliminarFavorito(int idjuego)
        {
            int idusuario = int.Parse(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
            this.service.DeleteFavorito(idjuego, idusuario);
            return RedirectToAction("Favoritos");
        }

    }
}

MvcUtopiaAWSAMH/Controllers/PlatosController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MvcUtopiaAWSAMH.Filters;
using MvcUtopiaAWSAMH.Services;
using NugetUtopia;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace MvcUtopiaAWSAMH.Controllers
{
    public class PlatosController : Controller
    {
        private ServiceApiUtopia service;

        public PlatosController(ServiceApiUtopia service)
        {
            this.service = service;
        }

        public async Task<IActionResult> Index()
        {
            List<Plato> platos = await this.service.GetPlatosAsync();
            return View(platos);
        }

        [AuthorizeUsuarios(Policy = "AdminOnly")]
        public IActionResult CrearPlato()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> CrearPlato(int idplato, string nombre, string descripcion, string categoria, int precio, IFormFile foto)
        {
            string filename = foto.FileName;
            string token = HttpContext.User.FindFirst("TOKEN").Value;
            Plato plato = new Plato();
            plato.IdPlato = idplato;
            plato.Nombre = nombre;
            plato.Descripcion = descripcion;
            plato.Categoria = categoria;
            plato.Precio = precio;
            plato.Foto = filename;
            await this.service.CrearPlatoAsync(plato, token);

            using (Stream stream = foto.OpenReadStream())
            {
                await this.service.UploadFile(stream, foto.FileName, "platos");
            }
            return RedirectToAction("Index", "Admin");
        }

        [AuthorizeUsuarios(Policy = "AdminOnly")]
        public async Task<ActionResult> DeletePlato(int idplato)
        {
            string token = HttpContext.User.FindFirst("TOKEN").Value;
            Plato plato = await this.service.FindPlatoAsync(idplato);
            await this.service.DeleteFileAsync(plato.Foto, "platos");
            await this.service.DeletePlatoAsync(idplato, token);
            return RedirectToAction("Index", "Admin");
        }

        [AuthorizeUsuarios(Policy = "AdminOnly")]
        public async Task<IActionResult> EditarPlato(int idplato)
        {
            Plato plato = await this.service.FindPlatoAsync(idplato);
            return View(plato);
        }

        [HttpPost]
        public async Task<IActionResult> EditarPlato(Plato plato, IFormFile archivo)
        {
            await this.service.DeleteFileAsync(plato.Foto, "platos");

            string filename = archivo.FileName;
            string token = HttpContext.User.FindFirst("TOKEN").Value;
            plato.Foto = filename;
            await this.service.UpdatePlatoAsync(plato, token);

            using (Stream stream = archivo.OpenReadStream())
            {
                await this.service.UploadFile(stream, archivo.FileName, "platos");
            }

            return RedirectToAction("Index", "Admin");
        }

    }
}

MvcUtopiaAWSAMH/Controllers/ReservasController.cs
using Amazon;
using Amazon.SimpleEmail;
using Amazon.SimpleEmail.Model;
using Microsoft.AspNetCore.Mvc;
using MvcUtopiaAWSAMH.Filters;
using MvcUtopiaAWSAMH.Services;
using NugetUtopia;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcUtopiaAWSAMH.Controllers
{
    public class ReservasController : Controller
    {
        private ServiceApiUtopia service;

        public ReservasController(ServiceApiUtopia service)
        {
            this.service = service;
        }

        #region Lado del Cliente
        [AuthorizeUsuarios]
        public IActionResult Index()
        {
            return View();
        }

        //Ejecuta el form para crear una reserva 
        //desde el lado del cliente. Ademas envia un correo de confirmacion
        [HttpPost]
        public async Task<IActionResult> Index(string nombre, string telefono, string email, int personas, DateTime fecha)
        {
            Reserva reserva = new Reserva();
            reserva.Nombre = nombre;
            reserva.Telefono = telefono;
            reserva.Email = email;
            reserva.Personas = personas;
            reserva.Fecha = fecha.ToShortDateString();
            reserva.Hora = fecha.ToShortTimeString();

            await this.service.CrearReservaAsync(reserva);
            //string asunto = "Reserva Utopia";
            //string mensaje = "<p>Hola " + nombre + "! Los datos de tu reserva son los siguientes:</p> <p> Día: " + fecha.ToShortDateString() + "</p><p>Hora: " + fecha.ToShortTimeString() + "</p><p> Número de asistentes: " + personas + "</p><p> Teléfono de contacto: " + telefono + "</p><p> Recuerda enseñar este correo en el local para verificar la reserva.</p><p> Esperemos que pases un gran día en Utopia! </p>";

            //var client = new AmazonSimpleEmailServiceClient(RegionEndpoint.USEast1);
            //Destination destination = new Destination();
            //destination.ToAddresses = new List<string> { email };
            //Message message = new Message();
            //message.Subject = new Content(asunto);
            //Body cuerpo = new Body();
            //cuerpo.Html = new Content(mensaje);
            //cuerpo.Text = new Content(mensaje);
            //message.Body = cuerpo;
            //SendEmailRequest request = new SendEmailRequest();
            //request.Source = "alvaro.moya@tajamar365.com";
            //request.Destination = destination;
            //request.Message = message;
            //SendEmailResponse response = await client.SendEmailAsync(request);

            //ViewData["CORREO"] = "<div><p>Hemos enviado un correo al email proporcionado. Por favor revisa tu bandeja de entrada y en caso de no haber ningun mensaje, mira en la carpeta spam</p></div>";

            return View();
        }
        #endregion

        #region Lado del Admin
        [AuthorizeUsuarios(Policy = "AdminOnly")]
        public IActionResult CrearReserva()
        {
            return View();
        }

        //Ejecuta el form para crear una reserva 
        //desde el panel del admin
        [HttpPost]
        public async Task<IActionResult> CrearReserva(string nombre, string telefono, string email, int personas, DateTime fecha)
        {
            Reserva reserva = new Reserva();
            reserva.Nombre = nombre;
            reserva.Telefono = telefono;
            reserva.Email = email;
            reserva.Personas = personas;
            reserva.Fecha = fecha.ToShortDateString();
            reserva.Hora = fecha.ToShortTimeString();

            await this.service.CrearReservaAsync(reserva);
            return RedirectToAction("Index", "Admin");
        }

        //Metodo para eliminar reservas
        [AuthorizeUsuarios(Policy = "AdminOnly")]
        public async Task<IActionResult> DeleteReserva(string nombre)
        {
            string token = HttpContext.User.FindFirst("TOKEN").Value;
            await this.service.DeleteReservaAsync(nombre, token);
            return RedirectToAction("Index", "Admin");
        }

        //Metodo para cargar datos de la reserva en el form editar
        [AuthorizeUsuarios(Policy = "AdminOnly")]
        public async Task<IActionResult> EditarReserva(string nombre)
        {
            string token = HttpContext.User.FindFirst("TOKEN").Value;
            Reserva reserva = await this.service.FindReservaAsync(nombre);
            return View(reserva);
        }

        //Metodo que ejecuta el form para editar la reserva
        [HttpPost]
        public async Task<IActionResult> EditarReserva(string nombre, string telefono, string email, int personas, DateTime fecha)
        {
            string token = HttpContext.User.FindFirst("TOKEN").Value;

            Reserva reserva = new Reserva();
            reserva.Nombre = nombre;
            reserva.Telefono = telefono;
            reserva.Email = email;
            reserva.Personas = personas;
            reserva.Fecha = fecha.ToShortDateString();
            reserva.Hora = fecha.ToShortTimeString();

            await this.service.UpdateReservaAsync(reserva, token);
           //string asunto = "Reserva Utopia";
           //string mensaje = "Hola " + nombre + "! Hemos modificado tu reserva siendo este el resultado final:</p> <p> Día: " + fecha.ToShortDateString() + "</p><p>Hora: " + fecha.ToShortTimeString() + "</p><p> Número de asistentes: " + personas + "</p><p> Teléfono de contacto: " + telefono + "</p><p> Recuerda enseñar este nuevo correo en el local para verificar la reserva. Puedes eliminar el correo anterior si asi lo deseas</p><p> Esperemos que pases un gran día en Utopia! </p>";

           //var client = new AmazonSimpleEmailServiceClient(RegionEndpoint.USEast1);
           //Destination destination = new Destination();
           //destination.ToAddresses = new List<string> { email };
           //Message message = new Message();
           //message.Subject = new Content(asunto);
           //Body cuerpo = new Body();
           //cuerpo.Html = new Content(mensaje);
           //cuerpo.Text = new Content(mensaje);
           //message.Body = cuerpo;
           //SendEmailRequest request = new SendEmailRequest();
           //request.Source = "alvaro.moya@tajamar365.com";
           //request.Destination = destination;
           //request.Message = message;
           //SendEmailResponse response = await client.SendEmailAsync(request);

            return RedirectToAction("Index", "Admin");
        }
        #endregion
    }
}

MvcUtopiaAWSAMH/Views/Shared/_Layout.cshtml
<!-- bootstrap core css -->
<link rel="stylesheet" type="text/css" href="~/css/bootstrap.css" />

<!--owl slider stylesheet -->
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
<!-- nice select  -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/css/nice-select.min.css" integrity="sha512-CruCP+TD3yXzlvvijET8wV5WxxEh5H8P4cmz0RFbKK6FlZ2sYl3AEsKlLPHbniXKSrDdFewhbmBK5skbdsASbQ==" crossorigin="anonymous" />
<!-- font awesome style -->
<link href="~/css/font-awesome.min.css" rel="stylesheet" />

<!-- Custom styles for this template -->
<link href="~/css/style.css" rel="stylesheet" />
<!-- responsive style -->
<link href="~/css/responsive.css" rel="stylesheet" />


<!-- header section strats -->
<header class="header_section" style="background-color: #222831 ">
    <div class="container">
        <nav class="navbar navbar-expand-lg custom_nav-container ">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                <span>
                    Utopia
                </span>
            </a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class=""> </span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav  mx-auto ">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Platos" asp-action="Index">Carta</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Juegos" asp-action="Index">Juegos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="SobreNosotros">Sobre nosotros</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Reservas" asp-action="Index">Reservar una mesa</a>
                    </li>
                    @if (Context.User.IsInRole("admin"))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Admin" asp-action="Index">Administrador</a>
                        </li>
                    }

                    @if (Context.User.Identity.IsAuthenticated == true)
                    {
                        <img src="https://bucket-utopia-amh.s3.amazonaws.com/images/users/@Context.User.FindFirst("Imagen").Value" style="border-radius:50%; width:5em;height:5em" />
                        <li class="nav-item">
                            <a class="nav-link" asp-action="DetallesUsuario" asp-controller="Usuarios">@Context.User.Identity.Name</a>
                        </li>
                    }

                </ul>

                <div class="user_option">
                    <a style="text-decoration:none;color:white" asp-controller="Juegos" asp-action="Favoritos">❤</a>
                    <a class="cart_link" asp-action="Carrito" asp-controller="Carrito">
                        <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 456.029 456.029" style="enable-background:new 0 0 456.029 456.029;" xml:space="preserve">
                        <g>
                        <g>
                        <path d="M345.6,338.862c-29.184,0-53.248,23.552-53.248,53.248c0,29.184,23.552,53.248,53.248,53.248
                   c29.184,0,53.248-23.552,53.248-53.248C398.336,362.926,374.784,338.862,345.6,338.862z" />
                    </g>
                  </g>
                        <g>
                        <g>
                        <path d="M439.296,84.91c-1.024,0-2.56-0.512-4.096-0.512H112.64l-5.12-34.304C104.448,27.566,84.992,10.67,61.952,10.67H20.48
                   C9.216,10.67,0,19.886,0,31.15c0,11.264,9.216,20.48,20.48,20.48h41.472c2.56,0,4.608,2.048,5.12,4.608l31.744,216.064
                   c4.096,27.136,27.648,47.616,55.296,47.616h212.992c26.624,0,49.664-18.944,55.296-45.056l33.28-166.4
                   C457.728,97.71,450.56,86.958,439.296,84.91z" />
                    </g>
                  </g>
                        <g>
                        <g>
                        <path d="M215.04,389.55c-1.024-28.16-24.576-50.688-52.736-50.688c-29.696,1.536-52.224,26.112-51.2,55.296
                   c1.024,28.16,24.064,50.688,52.224,50.688h1.024C193.536,443.31,216.576,418.734,215.04,389.55z" />
                    </g>
                  </g>
                        <g>
                  </g>
                        <g>
                  </g>
                        <g>
                  </g>
                        <g>
                  </g>
                        <g>
                  </g>
                        <g>
                  </g>
                        <g>
                  </g>
                        <g>
                  </g>
                        <g>
                  </g>
                        <g>
                  </g>
                        <g>
                  </g>
                        <g>
                  </g>
                        <g>
                  </g>
                        <g>
                  </g>
                        <g>
                  </g>
                </svg>
                    </a>
                    <partial name="_MenuUsuarioPartial" />
                </div>

            </div>
        </nav>
    </div>
</header>
<!-- end header section -->
@RenderBody()
<!-- footer section -->
<footer class="footer_section">
    <div class="container">
        <div class="row">
            <div class="col-md-4 footer-col">
                <div class="footer_contact">
                    <h4>
                        Contáctanos
                    </h4>
                    <div class="contact_link_box">
                        <a href="">
                            <i class="fa fa-phone" aria-hidden="true"></i>
                            <span>
                                +34 1234567890
                            </span>
                        </a>
                        <a href="">
                            <i class="fa fa-envelope" aria-hidden="true"></i>
                            <span>
                                utopiarestaurantes@gmail.com
                            </span>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-4 footer-col">
                <div class="footer_detail">
                    <a href="" class="footer-logo">
                        Utopia
                    </a>
                    <p>

                    </p>
                    <div class="footer_social">
                        <a href="https://www.twitter.com/utopia38679716">
                            <i class="fa fa-twitter" aria-hidden="true"></i>
                        </a>
                        <a href="https://www.instagram.com/utopia_madrid/">
                            <i class="fa fa-instagram" aria-hidden="true"></i>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-4 footer-col">
                <h4>
                    Horario
                </h4>
                <p>
                    Lunes-Viernes
                </p>
                <p>
                    10:00 Am -10:00 Pm
                </p>
                <p>
                    Domingos
                </p>
                <p>
                    10:00 Am -20:00 Pm
                </p>
            </div>
        </div>
        <div class="footer-info">
            <p>
                &copy; <span id="displayYear"></span> All Rights Reserved By
                <a href="https://html.design/">Utopia</a><br><br>
                &copy; <span id="displayYear"></span> Distributed By
                <a href="https://themewagon.com/" target="_blank">Utopia</a>
            </p>
        </div>
    </div>
</footer>
<!-- footer section -->
<!-- jQery -->
<script src="~/js/jquery-3.4.1.min.js"></script>
<!-- popper js -->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
</script>
<!-- bootstrap js -->
<script src="~/js/bootstrap.js"></script>
<!-- owl slider -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
</script>
<!-- isotope js -->
<script src="https://unpkg.com/isotope-layout@3.0.4/dist/isotope.pkgd.min.js"></script>
<!-- imask js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/imask/3.4.0/imask.min.js"></script>
<!-- nice select -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/js/jquery.nice-select.min.js"></script>
<!-- custom js -->
<script src="~/js/custom.js"></script>
<!--Sweetalert js-->
<script src="~/js/sweetalert2.all.min.js"></script>

MvcUtopiaAWSAMH/Views/Shared/_MenuUsuarioPartial.cshtml
@if (Context.User.Identity.IsAuthenticated == false)
{
    <div class="text-center">
        <a asp-controller="Home"
           asp-action="GoToHome"
           class="order_online">
            Log In
        </a>
    </div>
}
else
{
    <div class="text-center">
        <a asp-controller="Manage"
           asp-action="LogOut"
           class="order_online" style="background-color: #c41616">
            Log Out
        </a>
    </div>
}